### ISSUE TITLE
Strange 0.9.1 Release behavior

### ISSUE THREAD

**Issue by matxpa** [0xCUB3/About-This-Hack#42]
Hi @0xCUB3 

On a Hack Laptop MBP10,2, Monterey and Clover r5154 (ee2b479b1) a strange behavior with part of details

Your release 0.9.1

![Capture d’écran 2023-08-12 à 11 43 36](https://github.com/0xCUB3/About-This-Hack/assets/70573409/9d037e77-ed0a-4a22-ac3b-f1ebc650dc0b)

and with mine (older)

![Capture d’écran 2023-08-12 à 11 59 51](https://github.com/0xCUB3/About-This-Hack/assets/70573409/74bc7320-ceca-4c3f-9951-d306c46578c2)

Regards

**Comment by 0xCUB3** [comment]
Can you send me the output of

`sysctl -n machdep.cpu.brand_string`

in your Terminal?

**Comment by matxpa** [comment]
Hi
A second launch and a better result (?), but not for bootloader,  and with a third launch no right bootloader value

![Capture d’écran 2023-08-12 à 12 55 02](https://github.com/0xCUB3/About-This-Hack/assets/70573409/d60c7141-5916-4b24-aa09-0365c889d349)

And the result  of sysctl -n machdep.cpu.brand_string is right
Intel(R) Core(TM) i5-3340M CPU @ 2.70GHz

Regards

**Comment by 0xCUB3** [comment]
Hmm this is interesting. It's possible that the values aren't being stored quickly enough in the text file. I will try to create a fix for the next minor release.

**Comment by matxpa** [comment]
Hi
edit : to hide S.N on two screenshots.
Regards

**Comment by matxpa** [comment]
Hi @0xCUB3

Bootloader issue with Clover comes from HCBootloader.swift

Code line 20 :  BootloaderInfo = run("cat ~/.ath/scr.txt | grep \"Clover\" | awk '{print $4,\"r\" $6,\"(\" $9,\" \"}' | tr -d '\n'")

- "scr.txt" doesn't contain Clover needed infos but "hw.txt" does it. 
- No need to use "cat" command to open/read the file "grep" do it itself. So it could be

Code line 20 : BootloaderInfo = run("grep \"Clover\" ~/.ath/hw.txt | awk '{print $4,\"r\" $6,\"(\" $9,\" \"}' | tr -d '\n'")

Regards

**Comment by matxpa** [comment]
> Hmm this is interesting. It's possible that the values aren't being stored quickly enough in the text file. I will try to create a fix for the next minor release.

Hi
you're wright it happens only when "~/.ath" doesn't exist when you launch "About this Hack"
Regards

**Comment by 0xCUB3** [comment]
Hey @matxpa 
Could you try the latest commit? I think I fixed this bug along with some other issues.

**Comment by matxpa** [comment]
Hi @0xCUB3
I've just got the latest commits build "About this Hack" 
Issue #41 missing compiled version resolved

But #42 Strange 0.9.1 Release behavior is not resolved

First launch (without ~/.ath dir and data files needed)
![Capture d’écran 2023-09-03 à 19 19 52](https://github.com/0xCUB3/About-This-Hack/assets/70573409/6aa3e11c-eb4e-41a0-b865-0f8e05c43bca)
The timing doesn't work
Second launch (~/.ath dir and data files needed already present)
![Capture d’écran 2023-09-03 à 19 21 49](https://github.com/0xCUB3/About-This-Hack/assets/70573409/9a01c84e-f5d2-4760-a9fb-604131b59636)
But the lack of Clover BootLoader is not correct

Regards

**Comment by 0xCUB3** [comment]
This is very strange. I don't have Clover on any mac, so it is difficult for me to debug. Could you take a look into this issue if you have some time?

**Comment by matxpa** [comment]
Bootloader issue with Clover comes from HCBootloader.swift

Code line 20 is not correct

Code line 20 : BootloaderInfo = run("cat ~/.ath/scr.txt | grep \"Clover\" | awk '{print $4,\"r\" $6,\"(\" $9,\" \"}' | tr -d '\n'")

the data file "scr.txt" doesn't contain Clover needed infos but data file "hw.txt" does it and no need to use "cat" command to open/read the file "grep" do it itself. 

So it could be

Code line 20 : BootloaderInfo = run("grep \"Clover\" ~/.ath/hw.txt | awk '{print $4,\"r\" $6,\"(\" $9,\" \"}' | tr -d '\n'")


![Capture d’écran 2023-09-03 à 20 24 45](https://github.com/0xCUB3/About-This-Hack/assets/70573409/6a1ae332-dfe1-4584-918f-93192bebb2e8)



And to resolve the lack of detailed info at the first launch of the Appli (ie. without ~/.ath and needed data files)
I moved line code  Thread.sleep(forTimeInterval: 0.500) from 63rd position to 59th.
And the result is OK


I applied those two corrections in 
- HCBootloader.swift to resolve the lack of Clover Bootloader info
- ViewController.swift to resolve the lack of Memory, Display, Graphics detailed info (at a first launch in the absence of ~/.ath dir and data files)

And the result is ...

![Capture d’écran 2023-09-03 à 20 47 12](https://github.com/0xCUB3/About-This-Hack/assets/70573409/7e7d7f8a-21b0-42ab-a162-ff733264b9f5)
OK

And we all have to help each others


Regards

**Comment by 0xCUB3** [comment]
@matxpa I implemented your fixes; thank you so much!!!!!

I also have a bunch of other changes. Would you mind testing this latest build to see if everything is resolved? (You may also notice that the other tabs load much more quickly :) )
https://drive.google.com/file/d/1Yq_M2M6xOI0SOXwh1JlagsrzdC6XGxk0/view?usp=sharing

**Comment by matxpa** [comment]
@0xCUB3 

Sorry I'm late.
Fixes seem to be right on Overview
![Capture d’écran 2023-09-04 à 12 25 00](https://github.com/0xCUB3/About-This-Hack/assets/70573409/b6c1f653-e542-4281-9f3b-446ccf22f99b)
but at the first launch (without ~/.ath and the data files) one time the display is OK another time with partial content. I suspect the line 69        self.start(), in previous release self.start() was in     override func viewDidAppear() {

Otherwise at first launch even if OverView info are correctly displayed others tabs detail content isn't shown (Displays and Storage tabs)
![Capture d’écran 2023-09-04 à 18 03 42](https://github.com/0xCUB3/About-This-Hack/assets/70573409/2282aaa0-fd82-41df-8bb9-04f80d048165)


![Capture d’écran 2023-09-04 à 12 27 21](https://github.com/0xCUB3/About-This-Hack/assets/70573409/6d951063-aa84-40eb-bbaa-93e9283656c8)

With the previous release 0.9.1 he content of those two tabs was correct

![Capture d’écran 2023-09-04 à 12 30 52](https://github.com/0xCUB3/About-This-Hack/assets/70573409/dc6f41a2-449a-495f-ba1b-fabf3ab0dc57)

![Capture d’écran 2023-09-04 à 12 31 07](https://github.com/0xCUB3/About-This-Hack/assets/70573409/5ced714e-f912-443b-a8f3-49d964cd6875)

But that disk is not my startup disk, but an external ssd (USB3) empty (erased after a bad sonoma beta6 to beta7 update ) 
Her is my startup disk
![Capture d’écran 2023-09-04 à 18 35 13](https://github.com/0xCUB3/About-This-Hack/assets/70573409/7705c18d-3023-4b47-b321-2d714eab1d2f)

Regards

**Comment by matxpa** [comment]
@0xCUB3 

With the app you put on Google Drive the result is (at the first launch)
 
![Capture d’écran 2023-09-04 à 18 43 51](https://github.com/0xCUB3/About-This-Hack/assets/70573409/1e8d0015-ad17-4d4e-82c6-a4ddbc886a64)
No Graphics info

![Capture d’écran 2023-09-04 à 18 44 05](https://github.com/0xCUB3/About-This-Hack/assets/70573409/61057bb5-6887-40b8-83f2-467e712c66d5)
No Displays info

![Capture d’écran 2023-09-04 à 18 44 16](https://github.com/0xCUB3/About-This-Hack/assets/70573409/60699419-21ae-40c4-b5b3-f1443c7a9ab8)
No Statup Disk info

May be increase the sleep from 0.5 to 1 seconde, or the moment when each tab self.start() is executed.

FIY: The way to get OCLP info is detailed in #24 closed issue

Refards

**Comment by matxpa** [comment]
@0xCUB3 

With your second version put on Google Drive the result is (at the first launch)
Is OK for Overview and Displays tabs, but not for Storage.
My startup disk is a SSD and the picture shown is a HDD.

I tried a build with self.start() moved from line 69 to 82 in func viewDidAppear() and let sleep to 0.5 and at first launch Overview and Displays tabs content is OK.

**Comment by 0xCUB3** [comment]
so everything is fine if you put it there? No issues at all?

**Comment by matxpa** [comment]
I've done the same think on ViewControllerStorage.swift  (start() moved in func viewDidAppear()) the result is partial not completely OK as this (Stratup is a SSD not a HDD)
![Capture d’écran 2023-09-04 à 21 50 17](https://github.com/0xCUB3/About-This-Hack/assets/70573409/b2277120-a056-4645-a7ac-a1059df63002)

**Comment by 0xCUB3** [comment]
Interesting. I will have to look into why this is.

**Comment by matxpa** [comment]
Storage tab shows more details but Displays now is empty it's absolutely strange.
I'll suspect Ventura 13.6 (22G115) or Xcode 14.3.1 (14E300c)

**Comment by 0xCUB3** [comment]
Maybe. I wish I had this issue so I could dig deeper into its roots.

**Comment by matxpa** [comment]
@0xCUB3
Hi
About Storage tab : doesn't work if two or more Disk internal and/or external have the same name (ex: "Macintosh HD")

HardwareCollector.swift
...
static func getStorageType() -> Bool {
let name = "(HCStartupDisk.getStartupDisk())"
print("Startup Disk Name " + name)
let storageType = run("diskutil info "(name)" | grep 'Solid State'")

    return storageType.contains("Yes")
...

Startup disk is (and always were) "/" and (mine) is called "Macintosh HD"
So if i execute the command diskutil info "Macintosh HD" | grep "Solid State") as in HardwareCollector.swift
where "name" = "Macintosh HD", result is " Solid State: Info not available" so picture will be HDD (default)
'coz there are two SSD called "Macintosh HD", so
-Picture (startupDiskImage.image) has default value (HDD)
-storageValue.stringValue (startup disk name) is empty
-storageAmount.doubleValue is empty

With your first zipped App dowloaded yesterday Storage tab doesn't work with one or two SSD called "Macintosh HD"
With your second zipped App dowloaded yesterday Storage tab works fine with one SSD but doesn't with two SSD called "Macintosh HD".

Another thing:
I launch "About This Hack" (first launch) "/.ath" and data files are created Overview is shown with detailed data i change tab and launch Displays in remove (delete) "/.ath" ("About This Hack" always active) I come back to Overview I lost detailed info.
In ViewController.swift (line +/- 85 if (!HardwareCollector.dataHasBeenSet) {HardwareCollector.getAllData()}
I moved terminating bracket "}" after all variables init, (line +/- 149 after the line code serialToggle.isTransparent = true) and each time you show Overview variables content is not reloaded (it had been done at launch of the appli) so removing "~/.ath" causes No Problem.

And why "~/.ath" is not removed when you leave "About This Hack" between two launches data may have change.

PS: i don't know why words or sentences are crossed out and "~" is lost (github editor Pbm ?!)
Regards

**Comment by matxpa** [comment]
@0xCUB3 

In HardwareCollector.swift  you have to replace 
           "diskutil info \"\(name)\" | grep ..." 
with
           "grep ...   ~/.ath/sysvolname.txt"

HardwareCollector.swift 
...
    static func getStorageType() -> Bool {
        let name = "\(HCStartupDisk.getStartupDisk())"
        print("Startup Disk Name " + name)
//        let storageType = run("diskutil info \"\(name)\" | grep 'Solid State'")
        let storageType = run("grep 'Solid State' ~/.ath/sysvolname.txt")

        return storageType.contains("Yes")
        
    }


    static func getStorageData() -> [String] {
        let name = "\(HCStartupDisk.getStartupDisk())"
//        let size = run("diskutil info \"\(name)\" | grep 'Disk Size' | sed 's/.*:[[:space:]]*//' | cut -f1 -d'(' | tr -d '\n'")
        let size = run("grep 'Disk Size' ~/.ath/sysvolname.txt | sed 's/.*:[[:space:]]*//' | cut -f1 -d'(' | tr -d '\n'")
 //       let available = run("diskutil info \"\(name)\" | Grep 'Container Free Space' | sed 's/.*:[[:space:]]*//' | cut -f1 -d'(' | tr -d '\n'")
        let available = run("grep 'Container Free Space' ~/.ath/sysvolname.txt | sed 's/.*:[[:space:]]*//' | cut -f1 -d'(' | tr -d '\n'")
        let sizeTrimmed = run("echo \"\(size)\" | cut -f1 -d\" \"").dropLast(1)
        let availableTrimmed = run("echo \"\(available)\" | cut -f1 -d\" \"").dropLast(1)
        print("Size: \(sizeTrimmed)")
        print("Available: \(availableTrimmed)")
        let percent = (Double(availableTrimmed)!) / Double(sizeTrimmed)!
        print("%: \(1 - percent)")
        return ["""
        \(name)
        \(size)(\(available)Available)
        """, String(1 - percent)]
    }
...

And the result is at the first launch or not with one disk "Macintosh HD" or more than one called "Macintosh HD"

![Capture d’écran 2023-09-05 à 13 39 31](https://github.com/0xCUB3/About-This-Hack/assets/70573409/8b42051d-0933-4230-979c-c0b5a9303cb6)

Regards

**Comment by 0xCUB3** [comment]
@matxpa the latest commit should have all of the fixes you mentioned. Thank you for all the help. Please test if you can and let me know if there's anything else I should add.

**Comment by matxpa** [comment]
@0xCUB3
Hi
I've seen component HardwareCollector.swift had not been modified
 All or part of the "cat" commands remain
 In func getStorageData() remain use of diskutil instead of "grep .... ~/.ath/sysvolname.txt"

HardwareCollector.swift, is there a reason why two components called HardwareCollector.swift
 One inside the group "About This Hack" (old version from 0.9.0) and not used
 The other outside the group "About This Hack", this is the one in use and declared in TARGETS/Build Phases/Compile Sources.

Just cosmetic remarques
 In HCMacModelswift the "cartouche" remains (ie. //  HCMacModel.swift ...)
 mea-culpa In ViewController.swift : line 174         blVersion.toolTip   = blVersiontoolTip  (there's two spaces before =), it's my fault my own fault.

Regards

**Comment by 0xCUB3** [comment]
I didn't add that change because it was causing nil value errors.

**Comment by matxpa** [comment]
So with the component HardwareCollector.swift (outside of group "About This Hack") with remaining "cat" and "diskutil"
My material environment is 
  a 256 GB SSD with 22.9 GB free with Ventura it's the current macOS, it's the boot disk,
  a 120 GB SSD with 46.3 GB free, external SSD with Sonoma
the result is

![Capture d’écran 2023-09-11 à 15 13 57](https://github.com/0xCUB3/About-This-Hack/assets/70573409/28754553-888a-43fc-aff3-e361db96e8f5)

the first screenshot (upper one) is OK (SSD 256 GB) and component HardwareCollector.swift (outside of group "About This Hack") with "grep .... ~/.ath/sysvolname.txt" and not "diskutil"
the second screenshot (lower one) is KO (119.8 GB) it's not the boot disk and it's with component HardwareCollector.swift (outside of group "About This Hack") with remaining "cat" and "diskutil"

That situation 'cause the two SSD are called "Macintosh HD", and "diskutil info \"\(name)\" | Grep ..."  is not "diskutil info /" | grep ..." (/ ie. boot disk)
PS : second "diskutil into ... | Grep ... (Grep need to be replaced with grep)

Two others tabs (I suppose  Support remains OK (I joke))

Overview (OK)
![Capture d’écran 2023-09-11 à 15 38 09](https://github.com/0xCUB3/About-This-Hack/assets/70573409/252b4078-71dd-4142-b123-c9c4d6520656)

Displays (OK) event with "Unknown Dsiplay" (it's a just Hack not a 120% Mac) Resolution is OK (same as the one on Overview)
![Capture d’écran 2023-09-11 à 15 38 57](https://github.com/0xCUB3/About-This-Hack/assets/70573409/bcd14b19-fffd-49fe-9500-019c37e17587)

Sorry, I didn't see you answer
A "nil value" when you open Displays tab or at ATH launch ?
I don't have this issue

\~/.ath/sysvolname.txt contains only boot disk datas, this file can't be empty
\~/.ath/scrXml.txt and \~/.ath/scr.txt contain Graphics/Displays datas and can't by empty

I remarked that the creation of file "\~/.ath/version.txt" takes 1/2 seconde after all the others files creation

so in UpdateController.swift, create version.txt is not necessary
if you replace the two lines below
        _ = run("curl -o \~/.ath/version.txt https://raw.githubusercontent.com/0xCUB3/Website/main/content/ath.txt")
        let latestVersion = run("tr -d '[:space:]' < \~/.ath/version.txt")
with 
        let latestVersion = run("curl -s https://raw.githubusercontent.com/0xCUB3/Website/main/content/ath.txt | tr -d '[:space:]' ") or  | tr -d '\\n' (same result)

and 

replace (second run with latestVersion variable, and in the second run" tr -d  ..." is not necessary it was all ready done at creation of file "\~/.ath/version.txt" content) 
        _ = run("curl -L https://github.com/0xCUB3/About-This-Hack/releases/download/" + run("tr -d '[:space:]' <  ~/.ath/version.txt") + "/About.This.Hack.zip -o ~/.ath/new_ath.zip")
with
        _ = run("curl -L https://github.com/0xCUB3/About-This-Hack/releases/download/" +  latestVersion + "/About.This.Hack.zip -o ~/.ath/new_ath.zip")

In that ATH project (with your last modifications) I  rename the inside group HardwareCollector.swift in OLD-HardwareCollector.swift and move the outside group HardwareCollector.swift into group " About This Hack" and replace HardwareCollector.swift localisation (Path) in TARGETS/Build Phases/Compile Sources

Regards

**Comment by matxpa** [comment]
@0xCUB3  @MDNich @perez987 

Hi
A new  Storage tab (ATH build Xcode 15.0 b8)
![Capture d’écran 2023-09-13 à 12 01 21](https://github.com/0xCUB3/About-This-Hack/assets/70573409/4cce2de4-2cd7-4c48-a659-3b154ea6ce40)
HardwareCollector.swift component content modified

In my local Repo (a clone of yours) 
I removed HardwareCollector.swift component from  project TARGETS/Build Phases/Compile Sources section
I removed the inside group HardwareCollector.swift component
I moved  the outside group HardwareCollector.swift component into "About This Hack" group
I added HardwareCollector.swift reference project TARGETS/Build Phases/Compile Sources section

Regards

**Comment by 0xCUB3** [comment]
could you push your changes to your repo? They are not currently visible. Thank you!

**Comment by matxpa** [comment]
@0xCUB3 

Ok, i've done others modif.

1) No more text file for oclp datas, directly extracted from "OpenCore-Legacy-Patcher.plist" 
2) Overview i added info (Metal N) at Graphics and add graphicstoolTip too
3) Storage i added bootdisk storage info

Push : I can't sync (password authentication was removed on August 13, 2021.) with SmartGit (23.1 preview 12 #20104)

~/0xCUB3/About-This-Hack matxpa> git -c credential.helper=/Applications/SmartGit.app/Contents/Resources/credentials.sh push --porcelain --progress origin refs/heads/main:refs/heads/main
...
remote: Support for password authentication was removed on August 13, 2021.
Authentication failed for 'https://github.com/matxpa/About-This-Hack.git/'


I've created a new branch (from your main branch) called Storage-Tab-added-Data and i've modified components
be carefull project.pbx is with "Provisioning Profile" = None, no "Team" and "Signing Certficate" = ...Run Locally
 
Modified components (in new branch "Storage-Tab-added-Data")
About This Hack.xcodeproj

About This Hack/ViewController.swift
About This Hack/Tooltips.swift
About This Hack/HardwareCollector.swift (OLD one replaced by the current one)

About This Hack/HardwareCollectors/HCGPU.swift
About This Hack/HardwareCollectors/HCBootloader.swift
About This Hack/HardwareCollectors/HCStartupDisk.swift

Regards

**Comment by matxpa** [comment]
@0xCUB3 
Hi
ToolTip on GPU, not sure, some Hack with ATI GPU may have along Description.
'cause with OC or Clover you can set in your config.plist in Devices/Properties section a long model content
mine is "Intel HD Graphics 4000" and if i would i could set it to "Intel HD Graphics 4000 (Metal 5) iGPU from Intel(R) Core(TM) i5-3340M CPU @ 2.70GHz"  (it's improbable I grant it, but ...)

An other thing in HardwareCollector getStorageData() func

lines 130 & 131
        let percentfree = NSString(format: "%.2f",(((Double(availableTrimmed)!) / Double(sizeTrimmed)!) * 100))
        let percent = (Double(availableTrimmed)!) / Double(sizeTrimmed)!

may be replaced with somtehing like this to avoid two same calculation use
        let percent = (Double(availableTrimmed)!) / Double(sizeTrimmed)!
        let percentfree = NSString(format: "%.2f",(percent * 100))
Work fine, I tested it

And to finish is there a good reason to keep a component called HardwareCollector in "About This Hack" group unused component and not to move the component with same name from outside "About This Hack" group to inside group.

PS: OCLP is placed with BootLoader but it's logically relative to the OS with Version content (it's a System patch not a BootLoader patch).
Like this

![Capture d’écran 2023-09-13 à 22 40 29](https://github.com/0xCUB3/About-This-Hack/assets/70573409/f38ad2e0-ef87-4b23-bdb9-552ba55d7452)

Regards

**Comment by 0xCUB3** [comment]
I think I have a satisfactory amount of stuff done here. I am closing this issue and am ready for stable release :)

**Comment by 0xCUB3** [comment]
You can try this latest version: https://drive.google.com/file/d/1Yq_M2M6xOI0SOXwh1JlagsrzdC6XGxk0/view?usp=sharing

**Comment by matxpa** [comment]
@0xCUB3 Hi

https://drive.google.com/file/d/1Yq_M2M6xOI0SOXwh1JlagsrzdC6XGxk0/view?usp=sharing

I can't DL your Pre Release

Cette page ne fonctionne pas
Impossible de traiter cette demande via doc-0o-2s-docs.googleusercontent.com à l'heure actuelle.

HTTP ERROR 500

**Comment by 0xCUB3** [comment]
> @0xCUB3 Hi
> 
> 
> 
> https://drive.google.com/file/d/1Yq_M2M6xOI0SOXwh1JlagsrzdC6XGxk0/view?usp=sharing
> 
> 
> 
> I can't DL your Pre Release
> 
> 
> 
> Cette page ne fonctionne pas
> 
> Impossible de traiter cette demande via doc-0o-2s-docs.googleusercontent.com à l'heure actuelle.
> 
> 
> 
> HTTP ERROR 500

This is because I replaced it with a newer version in #39

**Comment by matxpa** [comment]
Yes but I can’t DL the one in in #39 for the same reason, with the same error

 

De : 0xCUBE ***@***.***>
Répondre à : 0xCUB3/About-This-Hack ***@***.***>
Date : samedi 16 septembre 2023 à 12:18
À : 0xCUB3/About-This-Hack ***@***.***>
Cc : Jean-Michel Meunier ***@***.***>, Mention ***@***.***>
Objet : Re: [0xCUB3/About-This-Hack] Strange 0.9.1 Release behavior (Issue #42)

 

@0xCUB3 Hi

https://drive.google.com/file/d/1Yq_M2M6xOI0SOXwh1JlagsrzdC6XGxk0/view?usp=sharing

I can't DL your Pre Release

Cette page ne fonctionne pas

Impossible de traiter cette demande via doc-0o-2s-docs.googleusercontent.com à l'heure actuelle.

HTTP ERROR 500

This is because I replaced it with a newer version in #39

**Comment by matxpa** [comment]
I finaly DL v1.0.0, test it all seem to be OK except a cosmetic thing on Graphics (no white space between MB and (Metal

 

De : 0xCUBE ***@***.***>
Répondre à : 0xCUB3/About-This-Hack ***@***.***>
Date : samedi 16 septembre 2023 à 12:18
À : 0xCUB3/About-This-Hack ***@***.***>
Cc : Jean-Michel Meunier ***@***.***>, Mention ***@***.***>
Objet : Re: [0xCUB3/About-This-Hack] Strange 0.9.1 Release behavior (Issue #42)

 

@0xCUB3 Hi

https://drive.google.com/file/d/1Yq_M2M6xOI0SOXwh1JlagsrzdC6XGxk0/view?usp=sharing

I can't DL your Pre Release

Cette page ne fonctionne pas

Impossible de traiter cette demande via doc-0o-2s-docs.googleusercontent.com à l'heure actuelle.

HTTP ERROR 500

This is because I replaced it with a newer version in #39

**Comment by 0xCUB3** [comment]
yeah all seems good except that people on older versions of macOS (high sierra) can't open the app because of the weird crash. I will need to fix that before a release.

**Comment by matxpa** [comment]
Perhaps  with this at Project Extracted from https://stackoverflow.com/questions/26024100/dyld-library-not-loaded-rpath-libswiftcore-dylib

 

In Target / Builds Settings / All Combined    Always Embed Swift Standard Libraries set to Yes

 

set the Embedded Content Contains Swift Code (EMBEDDED_CONTENT_CONTAINS_SWIFT) build setting to YES in your app as shown in Figure 2. This build setting, which specifies whether a target's product has embedded content with Swift code, tells Xcode to embed Swift standard libraries in your app when set to YES.

 

And on another page

With macOS High Sierra (10.13.6) you can run Xcode Version 10.1 (10B61). Xcode 10.1 includes Swift 4.2.1 and SDKs for iOS 12.1, watchOS 5.1, tvOS 12.1, and macOS Mojave.

So you can make and run Swift 4.2.1 based applications for macOS and iOS 12 but you can't use Swift 5.x or SwiftUI which started with Xcode 10.2 and Xcode 11.

 

Another one https://sarunw.com/posts/how-to-fix-dyld-library-not-loaded-error/

 

Another one https://developer.apple.com/forums/thread/52575

 

Regards

De : 0xCUBE ***@***.***>
Répondre à : 0xCUB3/About-This-Hack ***@***.***>
Date : samedi 16 septembre 2023 à 14:33
À : 0xCUB3/About-This-Hack ***@***.***>
Cc : Jean-Michel Meunier ***@***.***>, Mention ***@***.***>
Objet : Re: [0xCUB3/About-This-Hack] Strange 0.9.1 Release behavior (Issue #42)

 

yeah all seems good except that people on older versions of macOS (high sierra) can't open the app because of the weird crash. I will need to fix that before a release.

**Comment by 0xCUB3** [comment]
They seem to be having a different issue, though. We just have the wrong version. idk

**Comment by matxpa** [comment]
Did they try to compile ATH on H. Sierra with Flag Always Embed Swift Standard Libraries set to Yes ?

 

De : 0xCUBE ***@***.***>
Répondre à : 0xCUB3/About-This-Hack ***@***.***>
Date : samedi 16 septembre 2023 à 15:22
À : 0xCUB3/About-This-Hack ***@***.***>
Cc : Jean-Michel Meunier ***@***.***>, Mention ***@***.***>
Objet : Re: [0xCUB3/About-This-Hack] Strange 0.9.1 Release behavior (Issue #42)

 

They seem to be having a different issue, though. We just have the wrong version. idk
