### ISSUE TITLE
There is a problem with the RAM display.

### ISSUE THREAD

**Issue by Sher1ocks** [0xCUB3/About-This-Hack#47]
correct
[v0.8.1 Beta](https://github.com/0xCUB3/About-This-Hack/releases/tag/0.8.1)
![스크린샷 2023-09-01 오후 10 44 29](https://github.com/0xCUB3/About-This-Hack/assets/2107738/723cae2b-3527-4486-933f-c677b2c2a863)

wrong with latest version
[v0.9.1](https://github.com/0xCUB3/About-This-Hack/releases/tag/0.9.1)
![스크린샷 2023-09-01 오후 10 44 33](https://github.com/0xCUB3/About-This-Hack/assets/2107738/5eb24454-8ba5-44ab-ad2a-2e90ccd0b74d)

i think better v0.8.1 now.
also
Is it possible to change the feel of vector images to a smoother image border on macOS?
![스크린샷 2023-09-01 오후 10 47 02](https://github.com/0xCUB3/About-This-Hack/assets/2107738/389143a0-6e32-4f2a-90d5-29a007fd9f72)

thanks in advance

**Comment by 0xCUB3** [comment]
for the part about vectors, apple hasn't provided any vector images. I can try to convert it to a vector image but it rarely has the right effect.

**Comment by 0xCUB3** [comment]
@Sher1ocks what is the output you get if you put this in terminal: `cat ~/.ath/sysmem.txt`

**Comment by 0xCUB3** [comment]
Fixed the RAM issue in the latest commit. Now, if the speed shows up as "Empty" (apple's fault, not mine), that part will be omitted entirely in the output.

**Comment by Sher1ocks** [comment]
> Fixed the RAM issue in the latest commit. Now, if the speed shows up as "Empty" (apple's fault, not mine), that part will be omitted entirely in the output.

@0xCUB3 
issue still happen compared old verion
![스크린샷 2023-09-17 오전 11 18 21](https://github.com/0xCUB3/About-This-Hack/assets/2107738/467d3ccb-1296-48dd-a8c8-85dee35db312)

**Comment by 0xCUB3** [comment]
This is fine for now. The way we are collecting the data is different to increase performance, so it's fine that there is some stuff missing for some people as long as it doesn't say "empty"
